const dict = {
  en: {
    nav_features:'Features', nav_accounts:'Accounts', nav_screens:'Screens', nav_faq:'FAQ', nav_pricing:'Pricing', nav_integrations:'Integrations',
    badge:'Android live streaming studio',
    hero_title:'Professional mobile streaming. One app. Unlimited destinations.',
    hero_text:'Stream to YouTube, Twitch, Kick and any RTMP, RTSP, SRT or UDP server. Add multiple accounts for every platform and go live to several channels at the same time.',
    download:'Download', download_apk:'Download APK', explore:'Explore features', pill_accounts:'Multiple Accounts',
    accounts_eyebrow:'Main advantage', accounts_title:'Several accounts for every service',
    accounts_text:'Add two YouTube channels, several Twitch accounts, Kick accounts and custom servers. Enable only the destinations you need for each stream.',
    features_eyebrow:'Everything you need', features_title:'A complete mobile streaming studio',
    f_multi_title:'Multi-platform streaming', f_multi_text:'Broadcast to several platforms and custom destinations simultaneously.',
    f_accounts_title:'Multiple accounts', f_accounts_text:'Use multiple accounts from the same platform in one application.',
    f_sources_title:'Camera, screen, file', f_sources_text:'Stream from camera, screen capture or a local video file.',
    f_audio_title:'Audio control', f_audio_text:'Microphone, internal audio and mixed audio scenarios.',
    f_quality_title:'Professional quality', f_quality_text:'Resolution, FPS, bitrate and audio bitrate are fully configurable.',
    f_secure_title:'Secure setup', f_secure_text:'OAuth for supported platforms and hidden stream keys for custom destinations.',
    platforms_title:'Supported platforms and protocols', soon:'More soon', screens_eyebrow:'Design', screens_title:'Built for fast mobile control',
    compare_title:'Why creators choose StadFlow', c1:'Multiple accounts per platform', c2:'Multiple destinations at once', c4:'Camera, screen and video file', c5:'Mobile-first Android interface', c6:'Local recording option',
    q1:'Can I stream to multiple YouTube channels?', a1:'Yes. Add several YouTube accounts and enable the channels you need.',
    q2:'Can I use Twitch and Kick at the same time?', a2:'Yes. StadFlow is designed for simultaneous streaming to multiple destinations.',
    q3:'Can I stream to my own server?', a3:'Yes. Use custom RTMP, RTSP, SRT or UDP destinations.',
    cta_title:'Ready to go live?', cta_text:'Start streaming from your Android device to all your channels and accounts.',
    copyright:'© 2026 StadFlow. All rights reserved.',
    footer_legal:'Legal', footer_support:'Support', footer_product:'Product',
    pricing_title:'Simple Pricing', pricing_free:'Free', pricing_pro:'Pro', pricing_free_desc:'Perfect to start', pricing_pro_desc:'For professional creators',
    pricing_unlimited:'Unlimited destinations', pricing_watermark:'No watermark', pricing_high_bitrate:'Ultra-high bitrate',
    contact_title:'Contact Us', contact_text:'Have questions? We are here to help.',
    roadmap_title:'Product Roadmap', roadmap_next:'Coming Next', roadmap_done:'Completed',
    q4:'What is the maximum resolution supported?', a4:'StadFlow streams at up to 1080p at 60 FPS with a video bitrate of up to 8 Mbps. Use 720p / 30 FPS on mobile networks for the most stable stream.', q5:'Does StadFlow support internal audio capture?', a5:'Yes. On Android 10 and newer StadFlow can capture system audio when streaming your screen, and mix it with the microphone.', q6:'What is the difference between Free and Pro?', a6:'Free lets you stream to 2 destinations at once and shows ads. You can unlock a third destination temporarily by watching an ad. Pro removes all ads and lets you stream to unlimited destinations.', q7:'Is there a watermark?', a7:'No. StadFlow never adds a watermark to your stream, on any plan.', q8:'Can I record the stream locally?', a8:'Yes. Turn on "Save stream" in Settings and every broadcast is also saved to the Movies/StadFlow folder on your device.', q9:'Which Android version do I need?', a9:'Android 8.0 (API 26) or newer. Internal audio capture requires Android 10 or newer.', q10:'Does the stream stop when I lock the phone?', a10:'No. StadFlow runs as a foreground service and keeps streaming while the screen is off or you use other apps. Disable battery optimisation for StadFlow to be safe.', q11:'Where are my passwords and stream keys stored?', a11:'You never enter platform passwords in StadFlow — sign-in happens in the browser via OAuth. Tokens and stream keys are stored encrypted on your device and are never uploaded to our servers.', q12:'Why is the app not on Google Play?', a12:'StadFlow is currently distributed as a direct APK download while we prepare the Google Play release. The APK on this site is always the latest build.', faq_title:'Frequently Asked Questions', faq_lead:"Can't find an answer? Check the Help Center or contact us.", roadmap_lead:'What we are building next. Have a request? Tell us.', roadmap_progress:'In progress', changelog_lead:'Release history of the StadFlow Android app.', pricing_lead:'Start for free. Upgrade when you need more destinations.', pricing_free_streams:'2 destinations at once', pricing_free_extra:'+1 destination by watching an ad', pricing_ads:'Ads', pricing_no_ads:'No ads', pricing_all_features:'All streaming features', pricing_1080:'1080p 60 FPS, up to 8 Mbps', pricing_recording:'Local recording', pricing_priority:'Priority support', pricing_coming:'Coming soon', pricing_note:'Pro subscription is purchased inside the app via Google Play. Prices may vary by region.',
    changelog_title:'What\'s New', changelog_latest:'Latest Version'
  },
  ru: {
    nav_features:'Возможности', nav_accounts:'Аккаунты', nav_screens:'Экраны', nav_faq:'FAQ', nav_pricing:'Цены', nav_integrations:'Интеграции',
    badge:'Android-студия для прямых эфиров',
    hero_title:'Профессиональный мобильный стриминг. Одно приложение. Безлимитные назначения.',
    hero_text:'Стримьте на YouTube, Twitch, Kick и любые RTMP, RTSP, SRT или UDP серверы. Добавляйте несколько аккаунтов для каждой платформы и запускайте эфир сразу на несколько каналов.',
    download:'Скачать', download_apk:'Скачать APK', explore:'Смотреть возможности', pill_accounts:'Несколько аккаунтов',
    accounts_eyebrow:'Главное преимущество', accounts_title:'Несколько аккаунтов для каждого сервиса',
    accounts_text:'Добавляйте два YouTube-канала, несколько Twitch-аккаунтов, Kick-аккаунты и кастомные серверы. Для каждого эфира включайте только нужные назначения.',
    features_eyebrow:'Всё что нужно', features_title:'Полная мобильная студия для стрима',
    f_multi_title:'Мультиплатформенный стриминг', f_multi_text:'Одновременная трансляция на несколько платформ и кастомных назначений.',
    f_accounts_title:'Несколько аккаунтов', f_accounts_text:'Используйте несколько аккаунтов одной платформы в одном приложении.',
    f_sources_title:'Камера, экран, файл', f_sources_text:'Стримьте с камеры, захвата экрана или локального видеофайла.',
    f_audio_title:'Контроль аудио', f_audio_text:'Микрофон, внутренний звук и сценарии смешанного аудио.',
    f_quality_title:'Профессиональное качество', f_quality_text:'Разрешение, FPS, битрейт видео и аудио настраиваются отдельно.',
    f_secure_title:'Безопасная настройка', f_secure_text:'OAuth для поддерживаемых платформ и скрытые ключи трансляции для кастомных назначений.',
    platforms_title:'Поддерживаемые платформы и протоколы', soon:'Скоро больше', screens_eyebrow:'Дизайн', screens_title:'Создано для быстрого мобильного управления',
    compare_title:'Почему авторы выбирают StadFlow', c1:'Несколько аккаунтов на платформу', c2:'Несколько назначений одновременно', c4:'Камера, экран и видеофайл', c5:'Android-интерфейс mobile-first', c6:'Опция локальной записи',
    q1:'Можно стримить на несколько YouTube-каналов?', a1:'Да. Добавьте несколько YouTube-аккаунтов и включайте нужные каналы.',
    q2:'Можно использовать Twitch и Kick одновременно?', a2:'Да. StadFlow создан для одновременного стриминга на несколько назначений.',
    q3:'Можно стримить на свой сервер?', a3:'Да. Используйте кастомные RTMP, RTSP, SRT или UDP назначения.',
    cta_title:'Готов выйти в эфир?', cta_text:'Запускайте стрим с Android-устройства на все свои каналы и аккаунты.',
    copyright:'© 2026 StadFlow. Все права защищены.',
    footer_legal:'Юридическая информация', footer_support:'Поддержка', footer_product:'Продукт',
    pricing_title:'Цены', pricing_free:'Бесплатно', pricing_pro:'Pro', pricing_free_desc:'Для начала', pricing_pro_desc:'Для профессионалов',
    pricing_unlimited:'Безлимитные назначения', pricing_watermark:'Без водяного знака', pricing_high_bitrate:'Ультра-высокий битрейт',
    contact_title:'Контакты', contact_text:'Есть вопросы? Мы поможем.',
    roadmap_title:'План развития', roadmap_next:'В разработке', roadmap_done:'Готово',
    q4:'Какое максимальное разрешение поддерживается?', a4:'StadFlow стримит до 1080p при 60 FPS с битрейтом видео до 8 Мбит/с. В мобильных сетях используйте 720p / 30 FPS для максимальной стабильности.', q5:'Поддерживается ли захват внутреннего звука?', a5:'Да. На Android 10 и новее StadFlow захватывает системный звук при стриме экрана и может смешивать его с микрофоном.', q6:'Чем отличаются Free и Pro?', a6:'Free позволяет стримить на 2 назначения одновременно и показывает рекламу. Третье назначение можно временно открыть, посмотрев рекламу. Pro убирает всю рекламу и снимает лимит на количество назначений.', q7:'Есть ли водяной знак?', a7:'Нет. StadFlow никогда не добавляет водяной знак на стрим, ни на одном тарифе.', q8:'Можно ли записывать стрим локально?', a8:'Да. Включите «Сохранять стрим» в настройках — каждая трансляция будет также сохранена в папку Movies/StadFlow на устройстве.', q9:'Какая версия Android нужна?', a9:'Android 8.0 (API 26) или новее. Для захвата внутреннего звука нужен Android 10 или новее.', q10:'Стрим остановится, если заблокировать телефон?', a10:'Нет. StadFlow работает как foreground-сервис и продолжает стримить при выключенном экране или в других приложениях. На всякий случай отключите оптимизацию батареи для StadFlow.', q11:'Где хранятся пароли и ключи стрима?', a11:'Пароли платформ в StadFlow не вводятся — вход происходит в браузере через OAuth. Токены и ключи хранятся на устройстве в зашифрованном виде и никогда не отправляются на наши серверы.', q12:'Почему приложения нет в Google Play?', a12:'Сейчас StadFlow распространяется как APK, пока мы готовим релиз в Google Play. APK на этом сайте — всегда актуальная сборка.', faq_title:'Частые вопросы', faq_lead:'Не нашли ответ? Загляните в Центр помощи или напишите нам.', roadmap_lead:'Над чем мы работаем дальше. Есть пожелание? Напишите нам.', roadmap_progress:'В работе', changelog_lead:'История релизов Android-приложения StadFlow.', pricing_lead:'Начните бесплатно. Переходите на Pro, когда нужно больше назначений.', pricing_free_streams:'2 назначения одновременно', pricing_free_extra:'+1 назначение за просмотр рекламы', pricing_ads:'Реклама', pricing_no_ads:'Без рекламы', pricing_all_features:'Все функции стриминга', pricing_1080:'1080p 60 FPS, до 8 Мбит/с', pricing_recording:'Локальная запись', pricing_priority:'Приоритетная поддержка', pricing_coming:'Скоро', pricing_note:'Подписка Pro оформляется внутри приложения через Google Play. Цена может отличаться по регионам.',
    changelog_title:'Что нового', changelog_latest:'Последняя версия'
  },
  uk: {
    nav_features:'Можливості', nav_accounts:'Акаунти', nav_screens:'Екрани', nav_faq:'FAQ', nav_pricing:'Ціни', nav_integrations:'Інтеграції',
    badge:'Android-студія для прямих ефірів',
    hero_title:'Професійний мобільний стримінг. Один застосунок. Необмежені напрямки.',
    hero_text:'Транслюйте на YouTube, Twitch, Kick та будь-які RTMP, RTSP, SRT або UDP сервери. Додавайте кілька акаунтів для кожної платформи й виходьте в ефір одразу на кілька каналів.',
    download:'Завантажити', download_apk:'Завантажити APK', explore:'Переглянути можливості', pill_accounts:'Кілька акаунтів',
    accounts_eyebrow:'Головна перевага', accounts_title:'Кілька акаунтів для кожного сервісу',
    accounts_text:'Додавайте два YouTube-канали, кілька Twitch-акаунтів, Kick-акаунти та власні сервери. Для кожного ефіру вмикайте тільки потрібні напрямки.',
    features_eyebrow:'Усе що потрібно', features_title:'Повна мобільна студія для стримінгу',
    f_multi_title:'Мультиплатформний стримінг', f_multi_text:'Одночасна трансляція на кілька платформ і власних напрямків.',
    f_accounts_title:'Кілька акаунтів', f_accounts_text:'Використовуйте кілька акаунтів однієї платформи в одному застосунку.',
    f_sources_title:'Камера, екран, файл', f_sources_text:'Транслюйте з камери, запису екрана або локального відеофайлу.',
    f_audio_title:'Керування аудіо', f_audio_text:'Мікрофон, внутрішній звук і сценарії змішаного аудіо.',
    f_quality_title:'Професійна якість', f_quality_text:'Роздільна здатність, FPS, відео та аудіо бітрейт налаштовуються окремо.',
    f_secure_title:'Безпечне налаштування', f_secure_text:'OAuth для підтримуваних платформ і приховані ключі трансляції для власних напрямків.',
    platforms_title:'Підтримувані платформи та протоколи', soon:'Скоро більше', screens_eyebrow:'Дизайн', screens_title:'Створено для швидкого мобільного керування',
    compare_title:'Чому автори обирають StadFlow', c1:'Кілька акаунтів на платформу', c2:'Кілька напрямків одночасно', c4:'Камера, екран і відеофайл', c5:'Android-інтерфейс mobile-first', c6:'Опція локального запису',
    q1:'Можна стримити на кілька YouTube-каналов?', a1:'Так. Додайте кілька YouTube-акаунтів і вмикайте потрібні канали.',
    q2:'Можна використовувати Twitch і Kick одночасно?', a2:'Так. StadFlow створений для одночасного стримінгу на кілька напрямків.',
    q3:'Можна транслювати на свій сервер?', a3:'Так. Використовуйте власні RTMP, RTSP, SRT або UDP напрямки.',
    cta_title:'Готові вийти в ефір?', cta_text:'Запускайте стрим з Android-пристрою на все свої канали та акаунти.',
    copyright:'© 2026 StadFlow. Всі права захищені.',
    footer_legal:'Юридична інформація', footer_support:'Підтримка', footer_product:'Продукт',
    pricing_title:'Ціни', pricing_free:'Безкоштовно', pricing_pro:'Pro', pricing_free_desc:'Для початку', pricing_pro_desc:'Для професіоналів',
    pricing_unlimited:'Безлімітні напрямки', pricing_watermark:'Без водяного знаку', pricing_high_bitrate:'Ультра-високий бітрейт',
    contact_title:'Контакти', contact_text:'Є питання? Ми допоможемо.',
    roadmap_title:'План розвитку', roadmap_next:'В розробці', roadmap_done:'Готово',
    q4:'Яка максимальна роздільна здатність?', a4:'StadFlow стримить до 1080p при 60 FPS із бітрейтом відео до 8 Мбіт/с. У мобільних мережах використовуйте 720p / 30 FPS для максимальної стабільності.', q5:'Чи підтримується захоплення внутрішнього звуку?', a5:'Так. На Android 10 і новіше StadFlow захоплює системний звук під час стриму екрана і може змішувати його з мікрофоном.', q6:'Чим відрізняються Free і Pro?', a6:'Free дозволяє стримити на 2 напрямки одночасно і показує рекламу. Третій напрямок можна тимчасово відкрити, переглянувши рекламу. Pro прибирає всю рекламу і знімає ліміт на кількість напрямків.', q7:'Чи є водяний знак?', a7:'Ні. StadFlow ніколи не додає водяний знак на стрим, на жодному тарифі.', q8:'Чи можна записувати стрим локально?', a8:'Так. Увімкніть «Зберігати стрим» у налаштуваннях — кожна трансляція також буде збережена в папку Movies/StadFlow на пристрої.', q9:'Яка версія Android потрібна?', a9:'Android 8.0 (API 26) або новіше. Для захоплення внутрішнього звуку потрібен Android 10 або новіше.', q10:'Стрим зупиниться, якщо заблокувати телефон?', a10:'Ні. StadFlow працює як foreground-сервіс і продовжує стримити з вимкненим екраном або в інших застосунках. Про всяк випадок вимкніть оптимізацію батареї для StadFlow.', q11:'Де зберігаються паролі та ключі стриму?', a11:'Паролі платформ у StadFlow не вводяться — вхід відбувається в браузері через OAuth. Токени та ключі зберігаються на пристрої в зашифрованому вигляді й ніколи не надсилаються на наші сервери.', q12:'Чому застосунку немає в Google Play?', a12:'Зараз StadFlow розповсюджується як APK, поки ми готуємо реліз у Google Play. APK на цьому сайті — завжди актуальна збірка.', faq_title:'Часті запитання', faq_lead:'Не знайшли відповідь? Загляньте в Центр допомоги або напишіть нам.', roadmap_lead:'Над чим ми працюємо далі. Є побажання? Напишіть нам.', roadmap_progress:'У роботі', changelog_lead:'Історія релізів Android-застосунку StadFlow.', pricing_lead:'Почніть безкоштовно. Переходьте на Pro, коли потрібно більше напрямків.', pricing_free_streams:'2 напрямки одночасно', pricing_free_extra:'+1 напрямок за перегляд реклами', pricing_ads:'Реклама', pricing_no_ads:'Без реклами', pricing_all_features:'Усі функції стримінгу', pricing_1080:'1080p 60 FPS, до 8 Мбіт/с', pricing_recording:'Локальний запис', pricing_priority:'Пріоритетна підтримка', pricing_coming:'Незабаром', pricing_note:'Підписка Pro оформлюється всередині застосунку через Google Play. Ціна може відрізнятися за регіонами.',
    changelog_title:'Що нового', changelog_latest:'Остання версія'
  }
};
function setLang(lang){
  const strings=dict[lang]||dict.en;
  document.documentElement.lang=lang;
  localStorage.setItem('lang',lang);
  document.querySelectorAll('[data-i18n]').forEach(el=>{ const key=el.dataset.i18n; if(strings[key]){ if(el.children.length) el.innerHTML=strings[key].replace(/Help Center|Центр помощи|Центр допомоги/i, m=>'<a href="support.html">'+m+'</a>').replace(/contact us|напишите нам|напишіть нам|Tell us/i, m=>'<a href="contact.html">'+m+'</a>'); else el.textContent=strings[key]; } });
  document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));
}
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));
setLang(localStorage.getItem('lang') || 'en');
