const dict = {
  en: {
    nav_features:'Features', nav_accounts:'Accounts', nav_screens:'Screens', nav_faq:'FAQ', nav_pricing:'Pricing', nav_integrations:'Integrations',
    badge:'Android live streaming studio',
    hero_title:'Professional mobile streaming. One app. Unlimited destinations.',
    hero_text:'Stream to YouTube, Twitch, Kick and any RTMP, RTSP, SRT or UDP server. Add multiple accounts for every platform and go live to several channels at the same time.',
    download:'Download', download_apk:'Download APK', explore:'Explore features', pill_accounts:'Multiple Accounts',
    accounts_eyebrow:'Main advantage', accounts_title:'Several accounts for every service',
    accounts_text:'Add two YouTube channels, several Twitch accounts, Kick accounts and custom servers. Enable only the destinations you need for each stream.',
    features_eyebrow:'Everything you need', features_title:'A complete mobile streaming studio',
    f_multi_title:'Multi-platform streaming', f_multi_text:'Broadcast to several platforms and custom destinations simultaneously.',
    f_accounts_title:'Multiple accounts', f_accounts_text:'Use multiple accounts from the same platform in one application.',
    f_sources_title:'Camera, screen, file', f_sources_text:'Stream from camera, screen capture or a local video file.',
    f_audio_title:'Audio control', f_audio_text:'Microphone, internal audio and mixed audio scenarios.',
    f_quality_title:'Professional quality', f_quality_text:'Resolution, FPS, bitrate and audio bitrate are fully configurable.',
    f_secure_title:'Secure setup', f_secure_text:'OAuth for supported platforms and hidden stream keys for custom destinations.',
    platforms_title:'Supported platforms and protocols', soon:'More soon', screens_eyebrow:'Design', screens_title:'Built for fast mobile control',
    compare_title:'Why creators choose StadFlow', c1:'Multiple accounts per platform', c2:'Multiple destinations at once', c4:'Camera, screen and video file', c5:'Mobile-first Android interface', c6:'Local recording option',
    q1:'Can I stream to multiple YouTube channels?', a1:'Yes. Add several YouTube accounts and enable the channels you need.',
    q2:'Can I use Twitch and Kick at the same time?', a2:'Yes. StadFlow is designed for simultaneous streaming to multiple destinations.',
    q3:'Can I stream to my own server?', a3:'Yes. Use custom RTMP, RTSP, SRT or UDP destinations.',
    cta_title:'Ready to go live?', cta_text:'Start streaming from your Android device to all your channels and accounts.',
    copyright:'© 2024 StadFlow. All rights reserved.',
    footer_legal:'Legal', footer_support:'Support', footer_product:'Product',
    pricing_title:'Simple Pricing', pricing_free:'Free', pricing_pro:'Pro', pricing_free_desc:'Perfect to start', pricing_pro_desc:'For professional creators',
    pricing_unlimited:'Unlimited destinations', pricing_watermark:'No watermark', pricing_high_bitrate:'Ultra-high bitrate',
    contact_title:'Contact Us', contact_text:'Have questions? We are here to help.',
    roadmap_title:'Product Roadmap', roadmap_next:'Coming Next', roadmap_done:'Completed',
    changelog_title:'What\'s New', changelog_latest:'Latest Version'
  },
  ru: {
    nav_features:'Возможности', nav_accounts:'Аккаунты', nav_screens:'Экраны', nav_faq:'FAQ', nav_pricing:'Цены', nav_integrations:'Интеграции',
    badge:'Android-студия для прямых эфиров',
    hero_title:'Профессиональный мобильный стриминг. Одно приложение. Безлимитные назначения.',
    hero_text:'Стримьте на YouTube, Twitch, Kick и любые RTMP, RTSP, SRT или UDP серверы. Добавляйте несколько аккаунтов для каждой платформы и запускайте эфир сразу на несколько каналов.',
    download:'Скачать', download_apk:'Скачать APK', explore:'Смотреть возможности', pill_accounts:'Несколько аккаунтов',
    accounts_eyebrow:'Главное преимущество', accounts_title:'Несколько аккаунтов для каждого сервиса',
    accounts_text:'Добавляйте два YouTube-канала, несколько Twitch-аккаунтов, Kick-аккаунты и кастомные серверы. Для каждого эфира включайте только нужные назначения.',
    features_eyebrow:'Всё что нужно', features_title:'Полная мобильная студия для стрима',
    f_multi_title:'Мультиплатформенный стриминг', f_multi_text:'Одновременная трансляция на несколько платформ и кастомных назначений.',
    f_accounts_title:'Несколько аккаунтов', f_accounts_text:'Используйте несколько аккаунтов одной платформы в одном приложении.',
    f_sources_title:'Камера, экран, файл', f_sources_text:'Стримьте с камеры, захвата экрана или локального видеофайла.',
    f_audio_title:'Контроль аудио', f_audio_text:'Микрофон, внутренний звук и сценарии смешанного аудио.',
    f_quality_title:'Профессиональное качество', f_quality_text:'Разрешение, FPS, битрейт видео и аудио настраиваются отдельно.',
    f_secure_title:'Безопасная настройка', f_secure_text:'OAuth для поддерживаемых платформ и скрытые ключи трансляции для кастомных назначений.',
    platforms_title:'Поддерживаемые платформы и протоколы', soon:'Скоро больше', screens_eyebrow:'Дизайн', screens_title:'Создано для быстрого мобильного управления',
    compare_title:'Почему авторы выбирают StadFlow', c1:'Несколько аккаунтов на платформу', c2:'Несколько назначений одновременно', c4:'Камера, экран и видеофайл', c5:'Android-интерфейс mobile-first', c6:'Опция локальной записи',
    q1:'Можно стримить на несколько YouTube-каналов?', a1:'Да. Добавьте несколько YouTube-аккаунтов и включайте нужные каналы.',
    q2:'Можно использовать Twitch и Kick одновременно?', a2:'Да. StadFlow создан для одновременного стриминга на несколько назначений.',
    q3:'Можно стримить на свой сервер?', a3:'Да. Используйте кастомные RTMP, RTSP, SRT или UDP назначения.',
    cta_title:'Готов выйти в эфир?', cta_text:'Запускайте стрим с Android-устройства на все свои каналы и аккаунты.',
    copyright:'© 2024 StadFlow. Все права защищены.',
    footer_legal:'Юридическая информация', footer_support:'Поддержка', footer_product:'Продукт',
    pricing_title:'Цены', pricing_free:'Бесплатно', pricing_pro:'Pro', pricing_free_desc:'Для начала', pricing_pro_desc:'Для профессионалов',
    pricing_unlimited:'Безлимитные назначения', pricing_watermark:'Без водяного знака', pricing_high_bitrate:'Ультра-высокий битрейт',
    contact_title:'Контакты', contact_text:'Есть вопросы? Мы поможем.',
    roadmap_title:'План развития', roadmap_next:'В разработке', roadmap_done:'Готово',
    changelog_title:'Что нового', changelog_latest:'Последняя версия'
  },
  uk: {
    nav_features:'Можливості', nav_accounts:'Акаунти', nav_screens:'Екрани', nav_faq:'FAQ', nav_pricing:'Ціни', nav_integrations:'Інтеграції',
    badge:'Android-студія для прямих ефірів',
    hero_title:'Професійний мобільний стримінг. Один застосунок. Необмежені напрямки.',
    hero_text:'Транслюйте на YouTube, Twitch, Kick та будь-які RTMP, RTSP, SRT або UDP сервери. Додавайте кілька акаунтів для кожної платформи й виходьте в ефір одразу на кілька каналів.',
    download:'Завантажити', download_apk:'Завантажити APK', explore:'Переглянути можливості', pill_accounts:'Кілька акаунтів',
    accounts_eyebrow:'Головна перевага', accounts_title:'Кілька акаунтів для кожного сервісу',
    accounts_text:'Додавайте два YouTube-канали, кілька Twitch-акаунтів, Kick-акаунти та власні сервери. Для кожного ефіру вмикайте тільки потрібні напрямки.',
    features_eyebrow:'Усе що потрібно', features_title:'Повна мобільна студія для стримінгу',
    f_multi_title:'Мультиплатформний стримінг', f_multi_text:'Одночасна трансляція на кілька платформ і власних напрямків.',
    f_accounts_title:'Кілька акаунтів', f_accounts_text:'Використовуйте кілька акаунтів однієї платформи в одному застосунку.',
    f_sources_title:'Камера, екран, файл', f_sources_text:'Транслюйте з камери, запису екрана або локального відеофайлу.',
    f_audio_title:'Керування аудіо', f_audio_text:'Мікрофон, внутрішній звук і сценарії змішаного аудіо.',
    f_quality_title:'Професійна якість', f_quality_text:'Роздільна здатність, FPS, відео та аудіо бітрейт налаштовуються окремо.',
    f_secure_title:'Безпечне налаштування', f_secure_text:'OAuth для підтримуваних платформ і приховані ключі трансляції для власних напрямків.',
    platforms_title:'Підтримувані платформи та протоколи', soon:'Скоро більше', screens_eyebrow:'Дизайн', screens_title:'Створено для швидкого мобільного керування',
    compare_title:'Чому автори обирають StadFlow', c1:'Кілька акаунтів на платформу', c2:'Кілька напрямків одночасно', c4:'Камера, екран і відеофайл', c5:'Android-інтерфейс mobile-first', c6:'Опція локального запису',
    q1:'Можна стримити на кілька YouTube-каналов?', a1:'Так. Додайте кілька YouTube-акаунтів і вмикайте потрібні канали.',
    q2:'Можна використовувати Twitch і Kick одночасно?', a2:'Так. StadFlow створений для одночасного стримінгу на кілька напрямків.',
    q3:'Можна транслювати на свій сервер?', a3:'Так. Використовуйте власні RTMP, RTSP, SRT або UDP напрямки.',
    cta_title:'Готові вийти в ефір?', cta_text:'Запускайте стрим з Android-пристрою на все свої канали та акаунти.',
    copyright:'© 2024 StadFlow. Всі права захищені.',
    footer_legal:'Юридична інформація', footer_support:'Підтримка', footer_product:'Продукт',
    pricing_title:'Ціни', pricing_free:'Безкоштовно', pricing_pro:'Pro', pricing_free_desc:'Для початку', pricing_pro_desc:'Для професіоналів',
    pricing_unlimited:'Безлімітні напрямки', pricing_watermark:'Без водяного знаку', pricing_high_bitrate:'Ультра-високий бітрейт',
    contact_title:'Контакти', contact_text:'Є питання? Ми допоможемо.',
    roadmap_title:'План розвитку', roadmap_next:'В розробці', roadmap_done:'Готово',
    changelog_title:'Що нового', changelog_latest:'Остання версія'
  }
};
function setLang(lang){
  const strings=dict[lang]||dict.en;
  document.documentElement.lang=lang;
  localStorage.setItem('lang',lang);
  document.querySelectorAll('[data-i18n]').forEach(el=>{ const key=el.dataset.i18n; if(strings[key]) el.textContent=strings[key]; });
  document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));
}
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));
setLang(localStorage.getItem('lang') || 'en');
